---
name: Backend Tests

on: [ push ]

jobs:
  tests:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          working-directory: ./backend
          python -m pip install --upgrade pip
          ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key
          pip install -r backend/requirements.txt
      - name: Run migrations
        run: |
          working-directory: ./backend
          python manage.py migrate
      - name: Run tests
        run:
          pytest