---
name: Backend Tests

on:
  pull_request:
    branches:
      - develop
      - master

    paths-ignore:
      - "*.md"

jobs:
  docker:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          file-path: '/home/runner/work/cardflow/cardflow/frontend/.env'
      - uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          file-path: '/home/runner/work/cardflow/cardflow/backend/.env'
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          services: |
            backend
            postgres
      - name: Check containers
        run: |
          docker ps -a
          docker log cardflow-backend-1
      - name: Run tests
        run: |
          docker exec cardflow-backend-1 sh -c "pytest"
