---
name: Backend Tests

on:
  pull_request:
    branches:
      - develop
      - master

    paths-ignore:
      - "*.md"

jobs:
  docker:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start docker
        run: |
          sudo service docker start
          docker-compose --env-file "sample.env" up -d backend postgres
          sleep 10
      - name: Run tests
        run:
          pytest