---
name: Backend Tests

on:
  pull_request:
    branches:
      - develop
      - master

    paths-ignore:
      - "*.md"

jobs:
  docker:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-py/action-dotenv-to-setenv@v5
        with:
          env-file: sample.env
      - name: Start docker
        run: |
          docker-compose up -d backend postgres --build
      - name: Run tests
        run: pytest
