---
name: Backend Tests

on:
  pull_request:
    branches:
      - develop
      - master

    paths-ignore:
      - "*.md"

jobs:
  docker:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Start docker
        run: |
          sudo service docker start
          docker-compose up -d --build backend postgres

      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          cat ./sample.env > .env
      - name: Start docker
        working-directory: ./backend
        run: |
          docker-compose up -d backend postgres
          sleep 10

      - name: Run tests
        run:
          pytest