name: Frontend Tests

on:
  push:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"
  pull_request:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"

jobs:

   buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🗂️ Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: 🔨 Build
        run: npm run build
        working-directory: ./frontend

      - name: 🧪 Test
        run: npm test
        working-directory: ./frontend

      # Upload dist artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

      # Upload coverage artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/lcov.info