---
name: Backend Tests

on: [ push ]

jobs:
  tests:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          mkdir keys
          cd keys
          ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key
          cd ..
          pip install -r requirements.txt
      - name: Wait for PostgreSQL to be ready
        run: |
          timeout=300
          until pg_isready -h localhost -p 5432 -U postgres || ((timeout-- <= 0)); do
            sleep 1
          done
          test $timeout -gt 0
      - name: Run migrations
        working-directory: ./backend
        run: |
          python manage.py migrate
      - name: Run tests
        working-directory: ./backend
        env:
          SECRET_KEY: supersecretkey
        run:
          pytest