name: Frontend Tests

on:
  push:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"
  pull_request:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"

jobs:

   buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

    name: Setup Node.js
      - uses: actions/setup-node@v3
        with:
            node-version: 16
            cache: 'npm'


      
      -name: Change dir to frontend
        run: cd ./frontend

      - name: 🗂️ Install dependencies
        run: npm install

      - name: 🔨 Build
        run: npm run build

      - name: 🧪 Test
        run: npm test

      # Upload dist artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

      # Upload coverage artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/lcov.info