---
name: Backend Tests

on:
  pull_request:
    branches:
      - develop
      - master

    paths-ignore:
      - "*.md"

jobs:
  docker:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Create fucking frontend env file
        working-directory: frontend
        run: |
          cat sample.env >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: c-py/action-dotenv-to-setenv@v5
        with:
          env-file: sample.env
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          services: |
            backend
            postgres
#      - name: Start docker
#        run: |
#          docker-compose up -d --build postgres backend pgadmin4
      - name: Run tests
        run: pytest
